export let table = {
  tableName: 'lingyangshenqing',
  comment: '',
  comments: '领养申请',
  sfsh: '是',
  authPeople: '否',
  emailRegister: '否',
  hasCart: '否',
  thumbsUp: '否',
  storeUp: '否',
  browseClick: '否',
  hasHot: '无',
  virtualPay: '否',
  hasSales: false,
  selectSeat: '否',
  hasPay: '否',
  isReverse: '否',
  browseHistory: '否',
  limit: '否',
  vip: '否',
  jifen: '否',
  hasAlipay: '否',

  groupBuy: '否',
  creditScore: '否',
  authSeparate: '否',
  discuss: '否',
  location: '否',
  sessionReadTable: 'yonghu',
  merchantRole: '',
  homeSearch: '否',
  mapType: '无',
  hasChapter: '无',
  hasAuction: '否',
  hasMusic: '否',
  sharePlatform: '',
  hasChat: '无',
  collaborativeAction: '',
  fkMainTable: '',
  status: '',
  crossOptTableName: [],
  crossOptButton: [],
  crossOptAudit: [],
  crossOptPay: [],
  crossOptButtonStatusColumns: [],
  crossOptButtonTips: [],

  csuOperateList: ['修改'],
  csuTypeList: ['审核是'],
  csuUpdateTableList: ['lingyangchongwu'],
  csuUpdateColumnList: ['lingyangzhuangtai'],
  csuUpdateColumnTypeList: ['1'],
  csuUpdateColumnValueList: ['已领养'],
  csuConditionColumnList: ['chongwunicheng'],
  csuMessageList: ['该宠物已被领养'],
    
}

export let columns = [
  {
    columnName: 'shenqingbianhao',
    comments: '申请编号',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '自',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '32',
    detail_type: 'DetailTitle',
    detail_order: 2,
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'chongwunicheng',
    comments: '宠物昵称',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '是',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '16',
    detail_type: 'DetailText',
    detail_order: 0,
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'chongwupinzhong',
    comments: '宠物品种',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '是',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '32',
    detail_type: 'DetailText',
    detail_order: 0,
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'chongwutupian',
    comments: '宠物图片',
    type: '图',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '是',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '0',
    table_type: 'TableImage',
    form_type: 'YyFile',
    form_accept: 'image/*',
    formMaxCount: 3,
    imageRecognize: false, 
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'xingbie',
    comments: '性别',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '0',
    detail_type: 'DetailText',
    detail_order: 0,
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'xinggetedian',
    comments: '性格特点',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '0',
    detail_type: 'DetailText',
    detail_order: 0,
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'shenqingriqi',
    comments: '申请日期',
    type: '日',
    dateCurFlag: '是',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '[是]',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '0',
    detail_type: 'DetailText',
    detail_order: 0,
    form_type: 'YyDatePicker',
    form_showTime: false,
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'lingyangshuoming',
    comments: '领养说明',
    type: '多',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '0',
    detail_type: 'DetailText',
    detail_order: 0,
    form_type: 'YyTextArea',
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'zhanghao',
    comments: '账号',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: 'yonghu',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '是',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '0',
    detail_type: 'DetailUsername',
    detail_order: 0,
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'xingming',
    comments: '姓名',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '是',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '0',
    detail_type: 'DetailText',
    detail_order: 0,
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'shoujihaoma',
    comments: '手机号码',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '手',
    sort: '',
    sessionRead: '是',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '0',
    detail_type: 'DetailText',
    detail_order: 0,
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'sfsh',
    comments: '是否审核',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '是',
    encryption: '',
    courseFlag: '',
    columnDefault: '待审核',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    detail_type: 'DetailTag',
    detail_order: 0,
    table_type: 'TableTag',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [
      {
        value: '是',
        label: '已通过',
        type: 'success',
      },
      {
        value: '待审核',
        label: '待审核',
        type: 'info',
      },
      {
        value: '否',
        label: '未通过',
        type: 'danger',
      },
    ],
  },
  {
    columnName: 'shhf',
    comments: '审核回复',
    type: '多',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '是',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    detail_type: 'DetailText',
    detail_order: 0,
    form_type: 'YyTextArea',
    form_hidden: false,    
    options: [],
  },
]

export let searchColumns = [
  {
    queryFlagInput: ['是'],
    columnName: 'shenqingbianhao',
    comments: '申请编号',
    level: 0,
    refTable: '',
    refColumn: '',
    placeholder: '申请编号',
    form_type: 'YyText', 
    options: [],
  },

  {
    queryFlagInput: ['是'],
    columnName: 'chongwunicheng',
    comments: '宠物昵称',
    level: 0,
    refTable: '',
    refColumn: '',
    placeholder: '宠物昵称',
    form_type: 'YyText', 
    options: [],
  },

  {
    queryFlagInput: ['是'],
    columnName: 'chongwupinzhong',
    comments: '宠物品种',
    level: 0,
    refTable: '',
    refColumn: '',
    placeholder: '宠物品种',
    form_type: 'YyText', 
    options: [],
  },

  {
    queryFlagInput: ['是'],
    columnName: 'sfsh',
    comments: '是否通过',
    form_type: 'YySingleSelect',
    placeholder: '是否通过',
    options:[
      {
        value: '是',
        label: '是'
      },
      {
        value: '否',
        label: '否'
      },
      {
        value: '待审核',
        label: '待审核'
      },
    ]
  },
]

export let headerButtons = [
  {
    title: '新增',   
    name: '新增',
    key: 'add',
    iconName: 'Plus',
    className: 'action-add',
  },
]
export let tableButtons = []

/**
 * @description 课程表
 * titleNames: 标题
 * subTitleNames: 副标题
 * searchNames: 用权。显示的时候，根据这个条件过滤
 */ 
export let timeTable = {
  titleNames: [],
  subTitleNames: [],
  searchNames: []
}

export let detailConfig = {
  hasIsanon: false,
  titleName: 'chongwunicheng',
  titleNames: ['chongwunicheng','chongwupinzhong'],
  titleHeads: ['',''],
  imgName: 'chongwutupian',
  imgNames: ['chongwutupian'],
  pubPeopleName: 'zhanghao',
  sortName: '',
  sortOrder: 'desc',
  videoNames: [],
  inteltypeName: '',
  merchantName: '',
  payBtns: [
  ],
  hasBuyInput: false,
  actionBtns: [
    {
      title: '修改',    
      name: '修改',
      key: 'edit',
      iconName: 'Edit',
    },
    {
      title: '删除',
      name: '删除',
      key: 'remove',
      iconName: 'Delete',
    },
    {
      title: '审核',
      name: '审核',
      key: 'sfsh',
      iconName: 'DocumentChecked',
    },
  ],
  tabs: [
  ],
  sortList: [
  ]
}