/**
 * @description 登录、注册模块的角色信息列表
 */

export let roleList = [
  {
    hasBackLogin: "是",
    hasBackRegister: "否",
    hasFrontLogin: "否",
    hasFrontRegister: "否",
    roleName: "管理员",
    tableName: "users",
    faceMatch: '否',
    passwordProtected: '否',
    emailRegister: '否',
    accountName: 'username',
    avatarName: 'image',
    examName: 'username',      
  },
  {
    hasBackLogin: '否',
    hasBackRegister: '否',
    hasFrontLogin: '是',
    hasFrontRegister: '是',
    tableName: 'yonghu',
    roleName: '用户',
    faceMatch: '否',
    passwordProtected: '否',
    emailRegister: '是',
    accountName: 'zhanghao',
    accountComments: '账号',
    avatarName: 'touxiang',
    examName: 'zhanghao', 
  },
  {
    hasBackLogin: '是',
    hasBackRegister: '否',
    hasFrontLogin: '否',
    hasFrontRegister: '否',
    tableName: 'dianyuan',
    roleName: '店员',
    faceMatch: '否',
    passwordProtected: '否',
    emailRegister: '是',
    accountName: 'gonghao',
    accountComments: '工号',
    avatarName: 'touxiang',
    examName: 'gonghao', 
  },
]
