
const chartData = [
  {
    tableName: 'fuwudingdan',  
    xColumn: 'fuwumingcheng',  
    api: 'fuwudingdan/value/fuwumingcheng/jifen',  
    graphType: '竖',  
    showHome: true,
    title: '服务收入统计',  
    subNameList: [],  
    type: 'multiStatic',  
    typeSections: [],  
    hasMultiSeries: false,
    chartSort: '0',  
    func: '',  
    queryName: 'fuwuleixing',  
    queryRoles: [],  
  },
  {
    tableName: 'jiyangdingdan',  
    xColumn: 'fuwumingcheng',  
    api: 'jiyangdingdan/value/fuwumingcheng/jifen',  
    graphType: '折滑面',  
    showHome: true,
    title: '寄养收入统计',  
    subNameList: [],  
    type: 'multiStatic',  
    typeSections: [],  
    hasMultiSeries: false,
    chartSort: '0',  
    func: '',  
    queryName: 'fuwuleixing',  
    queryRoles: [],  
  },
  {
    tableName: 'chongwudingdan',  
    xColumn: 'chongwupinzhong',  
    api: 'chongwudingdan/value/chongwupinzhong/jifen',  
    graphType: '饼',  
    showHome: true,
    title: '宠物销售统计',  
    subNameList: [],  
    type: 'multiStatic',  
    typeSections: [],  
    hasMultiSeries: false,
    chartSort: '0',  
    func: '',  
    queryName: 'xiadanriqi',  
    queryRoles: [],  
  },
  {
    tableName: 'shangpindingdan',  
    xColumn: 'shangpinmingcheng',  
    api: 'shangpindingdan/value/shangpinmingcheng/jifen',  
    graphType: '漏',  
    showHome: true,
    title: '商品销售统计',  
    subNameList: [],  
    type: 'multiStatic',  
    typeSections: [],  
    hasMultiSeries: false,
    chartSort: '0',  
    func: '',  
    queryName: 'shangpinleixing',  
    queryRoles: [],  
  },
]
export default chartData