export let table = {
  tableName: 'forum',
  comment: '',
  comments: '宠物论坛',
  sfsh: '否',
  authPeople: '否',
  emailRegister: '否',
  detail: '否',
  foreEndList: '否',
  foreEndAdd: '否',
  jifen: '否',
  isReverse: '否',
  hasCart: '否',
  limit: '否',
  mulGraphType: '',
  virtualPay: '否',
  hasSales: false,
  vip: '否',
  groupBuy: '否',
  creditScore: '否',
  authSeparate: '是',
  tplist: '否',
  addHomePage: '否',
  hasPay: '否',
  hasAlipay: '否',
  hasRegister: '否',
  thumbsUp: '否',
  discuss: '否',
  storeUp: '是',
  statistics: '',
  mulStatistics: '',
  selectSeat: '否',
  menuJump: '列表',
  browseClick: '否',
  browseHistory: '否',
  foreEndListAuth: '是',
  location: '否',
  isAdmin: '否',
  sessionReadTable: '',
  merchantRole: '',
  exportExcel: '否',
  importExcel: '否',
  hasPrint: '否',
  frontLogin: '是',
  frontRegister: '是',
  backLogin: '是',
  backRegister: '是',
  homeSearch: '否',
  mapType: '无',
  homeStatistic: '无',
  passwordProtected: '否',
  tabBar: '否',
  hasChapter: '无',
  hasAuction: '否',
  hasHot: '无',
  hasMusic: '否',
  sharePlatform: '',
  hasChat: '无',
  collaborativeAction: '',
  fkMainTable: '',
  fixedAuth: '',
  passwordWrongNum: '0',
  buttons: '',
  imagePath: '轮播图/宠物',
  orderNum: '',
  status: '',

  titleName: '',

  crossOptTableName: [],
  crossOptButton: [],
  crossOptAudit: [],
  crossOptPay: [],
  crossOptButtonStatusColumns: [],
  crossOptButtonTips: [],

  csuOperateList: [],
  csuTypeList: [],
  csuUpdateTableList: [],
  csuUpdateColumnList: [],
  csuUpdateColumnTypeList: [],
  csuUpdateColumnValueList: [],
  csuConditionColumnList: [],
  csuMessageList: [],
}


export let columns = [
  {
    columnName: 'title',
    comments: '帖子标题',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '32',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'content',
    comments: '帖子内容',
    type: '编',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '否',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '256',
    table_type: 'TableHtml',
    form_type: 'YyQuill',
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'parentid',
    comments: '父节点id',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '0',
    unique: '',
    loginUser: '',
    formatValidation: '长',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'username',
    comments: '用户名',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'avatarurl',
    comments: '头像',
    type: '图',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '2,3,4,6,7',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    table_type: 'TableImage',
    form_type: 'YyFile',
    form_accept: 'image/*',
    formMaxCount: 3,
    imageRecognize: false, 
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'isdone',
    comments: '状态',
    type: '下',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '开放,关闭',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YySingleSelect', 
    form_hidden: false,    
    options: [
      {
        value: '开放',
        label: '开放',
      },
      {
        value: '关闭',
        label: '关闭',
      },
    ],
  },
  {
    columnName: 'istop',
    comments: '是否置顶',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '数',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '0',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    table_type: 'TableSwitch',
    form_type: 'YySwitch',
    form_hidden: false,    
    options: [
      {
        value: 0,
        label: '否'
      },
      {
        value: 1,
        label: '是'
      },
    ],
  },
  {
    columnName: 'toptime',
    comments: '置顶时间',
    type: '日长',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyDatePicker',
    form_showTime: true,
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'cover',
    comments: '封面',
    type: '图',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '32',
    table_type: 'TableImage',
    form_type: 'YyFile',
    form_accept: 'image/*',
    formMaxCount: 3,
    imageRecognize: false, 
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'isanon',
    comments: '是否匿名',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '数',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '0',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    table_type: 'TableSwitch',
    form_type: 'YySwitch',
    form_hidden: false,    
    options: [
      {
        value: 0,
        label: '否'
      },
      {
        value: 1,
        label: '是'
      },
    ],
  },
  {
    columnName: 'delflag',
    comments: '是否删除',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '数',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '0',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    table_type: 'TableSwitch',
    form_type: 'YySwitch',
    form_hidden: false,    
    options: [
      {
        value: 0,
        label: '否'
      },
      {
        value: 1,
        label: '是'
      },
    ],
  },
  {
    columnName: 'userid',
    comments: '用户id',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '长',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'storeupnum',
    comments: '收藏数',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '数',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '0',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
]

export let searchColumns = [
  {
    queryFlagInput: ['是'],
    columnName: 'title',
    comments: '帖子标题',
    level: 0,
    refTable: '',
    refColumn: '',
    placeholder: '帖子标题',
    form_type: 'YyText', 
    options: [],
  },
]
export let headerButtons = [
  {
    title: '新增',
    name: '新增',
    key: 'add',
    iconName: 'Plus',
    className: 'action-add',
  },
  {
    title: '删除',
    name: '删除',
    key: 'removes',
    iconName: 'Delete',
    className: 'action-removes',
  },
]
export let tableButtons = [
  {
    title: '查看',
    name: '查看',
    key: 'view',
    iconName: 'View',
    className: 'action-view',
  },
  {
    title: '删除',
    name: '删除',
    key: 'remove',
    className: 'action-delete',
    iconName: 'Delete',
  },
  {
    title: '修改', 
    name: '修改',
    key: 'edit',
    className: 'action-edit',
    iconName: 'Edit',
  },

  {
    title: '查看评论',  
    name: '查看评论',
    isPublic: true,
    key: 'forumDiscuss',
    iconName: 'ChatLineSquare',
  },
]

/**
 * @description 用权
 * titleNames: 标题
 * subTitleNames: 副标题
 * searchNames: 用权。显示的时候，根据这个条件过滤
 */ 
export let timeTable = {
  titleNames: [],
  subTitleNames: [],
  searchNames: []
}